### ISSUE TITLE
Making the bad point database more dynamic

### ISSUE THREAD

**Issue by bwgref** [NuSTAR/nustar-clock-utils#8]
It is hard-coded in the BAD_POINTS_DB.dat file at the moment, but it will need to be moved to some place more dynamic, to allow the interactive flagging of points

**Comment by matteobachetti** [comment]
At the moment, we do the following, mostly automatically:

1. We calculate the temperature-driven time delays
2. We pass a Savitzky-Golay (SG) filter through the residuals to find the additional local trends as a smooth curve
3. We sum the temperature correction to the smooth curve, run the resulting curve through a spline fit, and save the latter to the clock file

When we have bad clock points or bad divisor points, the SG filter gives strange spikes that deteriorate the clock correction instead of improving it.

We will need to create an interface that allows to:

1. Plot the current temperature delay function and compare it to clock offsets in one panel, and plot the residuals in another panel, as it is now in the clockfile page, but _without_ the additional SG detrending, to clearly show where the problematic clock measurements and divisor values are.
2. Being able to flag bad clock measurements interactively, and immediately calculate the new SG curve, hopefully smoother than before.
3. Correct divisor values where they are clearly off wrt the commanded ones
